spring.datasource.url=jdbc:postgresql://localhost:5432/billing_db
spring.datasource.username=billing_user
spring.datasource.password=billing_pass

logging.level.com.billing.invoice_manager=DEBUG
logging.level.org.hibernate.SQL=DEBUG
spring.jpa.show-sql=true